# -*- coding: utf-8 -*-
"""
/***************************************************************************
 waterManager
                                 A QGIS plugin
 this plugin willl allow users to load community dataset and water source dataset and process and give them the results for the nearest water sorce for communities
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-11-30
        copyright            : (C) 2024 by group10
        email                : danielkasambala51@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load waterManager class from file waterManager.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .water_manager import waterManager
    return waterManager(iface)
